# Generated by Django 5.2.17 on 2026-09-30 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('po', 'Purchase Order'), ('nota', 'Nota Pembelian'), ('invoice', 'Invoice')], max_length=10)),
                ('number', models.CharField(editable=False, max_length=40, unique=True)),
                ('date', models.DateField(verbose_name='Tanggal')),
                ('party', models.CharField(max_length=200, verbose_name='Nama')),
                ('addr', models.TextField(blank=True, verbose_name='Alamat')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telepon')),
                ('notes', models.TextField(blank=True, verbose_name='Keterangan')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama')),
                ('qty', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Jumlah')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Satuan')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Harga / Nilai')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='docs.document')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
